### ISSUE TITLE
Example Custom Configs

### ISSUE THREAD

**Issue by Vaulto350** [RazoomGD/geode-object-groups#3]
I think having a few (usable) examples of custom configurations would be really beneficial.

Mostly because I have no clue how any of it works, and it's a pain in the ass on android

**Comment by RazoomGD** [comment]
Yeah. Making configuration is a great pain. I spent about 6 hours making the default one.

I have plans to add more examples of configuration in the future updates. I also wanna make so that people could share their configuration files on my Discord server. But now I am waiting for Geode admins to approve this mod so that it appears in the game.

**Comment by RazoomGD** [comment]
> Mostly because I have no clue how any of it works, and it's a pain in the ass on android

Btw, there is a [guide](https://github.com/RazoomGD/geode-object-groups/blob/main/Configuring%20Object%20Groups.md) explaining how this works. I think with this guide it should be clear
